
Template.instanceform_table.helpers InstanceformTemplate.helpers

Template.instanceform_table.onCreated InstanceformTemplate.onCreated

Template.instanceform_table.onRendered InstanceformTemplate.onRendered

Template.instanceform_table.events InstanceformTemplate.events