
Template.instanceform.helpers InstanceformTemplate.helpers

Template.instanceform.onCreated InstanceformTemplate.onCreated

Template.instanceform.onRendered InstanceformTemplate.onRendered

Template.instanceform.events InstanceformTemplate.events