image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6000
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 6379
    onOpen: ignore
  - port: 27017
    onOpen: ignore
  - port: 3100 # Creator
    onOpen: open-browser
    visibility: public
  - port: 16686 # Jaeger UI
    onOpen: open-browser
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
  - port: 80
    onOpen: ignore
    visibility: public
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Docker
    command: |
      echo "ROOT_URL=$(gp url 6000)" >> .env.local 
      echo "METADATA_SERVER=$(gp url 6000)" >> .env.local
      echo "ROOT_URL=$(gp url 80)" >> deploy/enterprise/.env 
      yarn docker:db
  - name: Steedos
    init: |
      yarn
    command: |
      git config pull.rebase false
      rm creator/.env.local
      cp creator/.env creator/.env.local
      sed -i "/^ROOT_URL=*/cROOT_URL=$(gp url 3100)" creator/.env.local
      yarn install
      yarn build
      gp await-port 27017
      gp await-port 6379
      yarn start
vscode:
  extensions:
    - dbaeumer.vscode-eslint
