declare var Meteor;
declare var SimpleSchema;
declare var Match;
declare var Creator;
declare var Steedos;
declare var WebApp;
declare var WebAppInternals;
declare var __meteor_runtime_config__;
declare var TAPi18n;
