Creator.Objects.vip_card =
	name: "vip_card"
	label: "会员卡"
	icon: "apps"
	fields:
        card_number:
            label:"卡号"
            type:'text'
            required:true
            omit:true
        points:
            label:'积分'
            type:'number'
            omit:true
        grade:
            label:'等级'
            type:'text'
            omit:true
        discount:
            label:'折扣'
            type:'text'
            omit:true
        balance:
            label:'余额'
            type:'number'
            omit:true
        start_store:
            label:'办卡门店'
            type:'lookup'
            reference_to:'vip_store'
            omit:true
        apply_stores:
            label:'适用门店'
            type:'lookup'
            reference_to:'vip_store'
            mutiple:true
            omit:true
        start_time:
            label:'办卡时间'
            type:'datetime'
            omit:true
        end_time:
            label:'有效时间'
            type:'datetime'
            omit:true
        user:
            label:'持卡人'
            type:'lookup'
            reference_to:'users'
            omit:true
        introducer:
            label:'推荐人'
            type:'lookup'
            reference_to:'users'
            omit:true
        is_actived:
            label:'是否激活'
            type:'text'
            omit:true
        actived_time:
            label:'激活时间'
            type:'datetime'
            omit:true
        enable_share:
            label:'是否共享'
            type:'Boolean'
            defaultValue:false
