version: "3.9"

services:


  steedos-enterprise:
    image: steedos/steedos-community:latest
    ports:
      - "80:80"
      - "9001:9001"
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - ROOT_URL=

    tty: true
    volumes:
      - "./steedos-storage:/steedos-storage"
