version: "3.9"

services:

  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  steedos-enterprise:
    image: steedos/steedos-enterprise:latest
    ports:
      - "9080:80"
      - "9001:9001"
    build: 
      context: ./
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
    labels:
      - traefik.enable=true
      - traefik.http.routers.steedos.rule=PathPrefix(`/`)
      - traefik.http.routers.steedos.entrypoints=web
      - traefik.http.services.steedos.loadbalancer.server.port=80
    environment:
      - STEEDOS_LICENSE=
      - STEEDOS_UNPKG_URL=/unpkg
      - NPM_CACHE_ENABLED=true
      # - NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
      - STEEDOS_WIDGETS_ADDITIONAL=@steedos-widgets/liveblocks@6.3.11-beta.20
      # - B6_SERVER_VERSION=0.11.5
      # - B6_PLUGIN_PACKAGES=@builder6/node-red,lodash
      # - B6_PLUGIN_SERVICES=@builder6/node-red
      # - B6_PLUGIN_MODULES=@builder6/node-red
      # - STEEDOS_NODERED_ENABLED=false
      # - B6_OIDC_ENABLED=false
      # - B6_OIDC_ISSUER=https://id.steedos.cn/realms/master
      # - B6_OIDC_CLIENT_ID=steedos-oidc-public
      # - B6_OIDC_CLIENT_SECRET=none
      # - B6_OIDC_NAME=Steedos ID
      # - B6_OIDC_LABEL=Steedos ID
      # - B6_OIDC_LOGO=https://www.steedos.com/favicon.png

    tty: true
    volumes:
      - "./steedos-storage:/steedos-storage"
  
volumes:
  portainer_data:
    driver: local