version: "3.9"

services:
  steedos-enterprise:
    image: steedos/steedos-enterprise:latest
    ports:
      - "80:80"        # Nginx
      - "9001:9001"    # Supervisor
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
    volumes:
      - "./steedos-storage:/steedos-storage"
  
volumes:
  steedos-mongodb:
    driver: local