open https://npm.taobao.org/sync/@steedos/app-admin
open https://npm.taobao.org/sync/@steedos/app-contracts
open https://npm.taobao.org/sync/@steedos/app-crm
open https://npm.taobao.org/sync/@steedos/app-oa
open https://npm.taobao.org/sync/@steedos/app-okr-management
open https://npm.taobao.org/sync/@steedos/app-project-management
open https://npm.taobao.org/sync/steedos-project-template
open https://npm.taobao.org/sync/@steedos/accounts
open https://npm.taobao.org/sync/@steedos/auth
open https://npm.taobao.org/sync/@steedos/client
open https://npm.taobao.org/sync/@steedos/core
open https://npm.taobao.org/sync/create-steedos-app
open https://npm.taobao.org/sync/@steedos/design-system-react
open https://npm.taobao.org/sync/@steedos/filters
open https://npm.taobao.org/sync/@steedos/formula
open https://npm.taobao.org/sync/@steedos/i18n
open https://npm.taobao.org/sync/@steedos/meteor-bundle-dependencies
open https://npm.taobao.org/sync/@steedos/meteor-bundle-runner
open https://npm.taobao.org/sync/@steedos/migrate
open https://npm.taobao.org/sync/@steedos/objectql
open https://npm.taobao.org/sync/@steedos/plugin-enterprise
open https://npm.taobao.org/sync/@steedos/process
open https://npm.taobao.org/sync/@steedos/project-template-empty
open https://npm.taobao.org/sync/@steedos/react
open https://npm.taobao.org/sync/@steedos/schemas
open https://npm.taobao.org/sync/@steedos/standard-objects
open https://npm.taobao.org/sync/@steedos/tailwind
open https://npm.taobao.org/sync/@steedos/webapp
open https://npm.taobao.org/sync/steedos-server