version: "3.9"

services:

  steedos:
    image: steedos/steedos-enterprise:3.0.0-beta.63
    ports:
      - "5000:80"    # Steedos
      - "27017:27017"  # MongoDB
      - "9001:9001"    # Supervisor
      - "6379:6379"    # Redis
    env_file:
      - .env
      - .env.local
    environment:
      - STEEDOS_WIDGETS_ADDITIONAL=@steedos-widgets/liveblocks
      - STEEDOS_AUTH_COOKIES_USE_SAMESITE=None
      - STEEDOS_TENANT_ENABLE_REGISTER=false
      - STEEDOS_TENANT_ENABLE_CREATE_TENANT=false
      - B6_PORT=5100
      - B6_MO_LOG_LEVEL=warn
      - STEEDOS_INITIAL_PACKAGES=file:/steedos-packages/media-report,file:/steedos-packages/sync_orgs_users
    volumes:
      - "./steedos-storage:/steedos-storage"
      - "../steedos-packages:/steedos-packages"