name: NPM Release

on:
  push:
    tags:
     - 'v2.7.**'
     - 'v3.0.**'

jobs:
  npm-release:
    runs-on: ubuntu-latest
    steps:
    
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Check valid tag format
        if: steps.version.outputs.is_valid == 'false'
        run: exit 1

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2
        with: 
          strip_tag_prefix: v

      - name: Get the current tag
        if: steps.branch-name.outputs.is_tag == 'true'  # Replaces: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "tag: ${{ steps.branch-name.outputs.tag }}"
          echo "current_branch: ${{ steps.branch-name.outputs.current_branch }}"
          echo "ref_branch: ${{ steps.branch-name.outputs.ref_branch }}"

      # checkout branch 3.0
      - name: 3.0 Checkout branch 3.0
        uses: actions/checkout@v2
        if: ${{ startsWith(steps.branch-name.outputs.tag, '3.0') }} 
        with: 
          ref: '3.0'

      # checkout branch 2.7
      - name: Checkout branch 2.7
        uses: actions/checkout@v2
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') }} 
        with: 
          ref: '2.7'

      - name: 3.0 Use Node.js 22
        uses: actions/setup-node@v4
        if: ${{ startsWith(steps.branch-name.outputs.tag, '3.0') }} 
        with:
          # 使用上一步骤中设置的输出变量
          node-version: 22
          cache: "yarn"

      # 步骤 2: 使用确定的 Node.js 版本
      - name: 2.7 Use Node.js 14
        uses: actions/setup-node@v4
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') }} 
        with:
          # 使用上一步骤中设置的输出变量
          node-version: 14
          cache: "yarn"

      - name: Build platform 2.7
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') }} 
        run: |
          yarn --frozen-lockfile
          yarn bootstrap
          yarn build

      - name: Build platform 3.0
        if: ${{ startsWith(steps.branch-name.outputs.tag, '3.0') }} 
        run: |
          yarn install --immutable
          yarn build

      - name: Lerna publish 2.7
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') && steps.version.outputs.is_stable == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          yarn lerna publish ${{ steps.branch-name.outputs.tag }}  --no-git-tag-version --no-git-reset --force-publish --exact --yes --registry https://registry.npmjs.org
          git add . 
          git commit -m "action: release ${{ steps.branch-name.outputs.tag }}"
          git push
        env:
          CI: false
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Lerna publish 3.0
        if: ${{ startsWith(steps.branch-name.outputs.tag, '3.0') && steps.version.outputs.is_stable == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          yarn lerna publish ${{ steps.branch-name.outputs.tag }}  --no-git-tag-version --no-git-reset --force-publish --exact --yes --registry https://registry.npmjs.org
          git add . 
          git commit -m "action: release ${{ steps.branch-name.outputs.tag }}"
          git push
        env:
          CI: false
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
            
      - name: Lerna publish beta
        if: ${{ steps.version.outputs.is_stable != 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          yarn lerna publish ${{ steps.branch-name.outputs.tag }}  --no-git-tag-version --no-git-reset --force-publish --exact --yes --dist-tag beta --registry https://registry.npmjs.org
          git add . 
          git commit -m "build: release ${{ steps.branch-name.outputs.tag }}"
          git push
        env:
          CI: false
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  docker-release:
    runs-on: ubuntu-latest
    needs: npm-release 
    steps:

      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2
        with: 
          strip_tag_prefix: v

      # checkout branch 2.7
      - name: Checkout branch 2.7
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') }} 
        uses: actions/checkout@v2
        with: 
          ref: '2.7'

      # checkout branch 3.0
      - name: Checkout branch 3.0
        if: ${{ startsWith(steps.branch-name.outputs.tag, '3.0') }} 
        uses: actions/checkout@v2
        with: 
          ref: '3.0'

      - name: Set Current Version
        run: |
          STEEDOS_VERSION=$(node -p 'require("./lerna.json").version')
          echo "STEEDOS_VERSION=${STEEDOS_VERSION}" >> $GITHUB_ENV
          echo "STEEDOS_VERSION=${STEEDOS_VERSION}"
        
      - name: Generate info.json
        run: |
          if [[ -f deploy/enterprise/scripts/generate_info_json.sh ]]; then
            deploy/enterprise/scripts/generate_info_json.sh
          fi

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            steedos/steedos-community
            steedos/steedos-enterprise
          tags: |
            type=semver,pattern={{version}},value=${{ env.STEEDOS_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.STEEDOS_VERSION }}
            type=semver,pattern={{major}},value=${{ env.STEEDOS_VERSION }}

      - uses: docker/login-action@v1
        name: Login Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Replace Version ~3.0 to Tag
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: deploy/enterprise/app/platform/package.json
          find: "~3.0"
          replace: ${{env.STEEDOS_VERSION}}
          regex: false

      - name: Build and push docker
        uses: docker/build-push-action@v6
        if: ${{ steps.version.outputs.is_stable != 'true' }}
        with:
          context: ./deploy/enterprise
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # 正式版才发布 arm64
      - name: Build and push docker
        uses: docker/build-push-action@v6
        if: ${{ steps.version.outputs.is_stable == 'true' }}
        with:
          context: ./deploy/enterprise
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  docker-sync:
    runs-on: ubuntu-latest
    needs: docker-release
      
    steps:

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2
        with: 
          strip_tag_prefix: v

      # checkout branch 2.7
      - name: Checkout branch 2.7
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') }} 
        uses: actions/checkout@v2
        with: 
          ref: '2.7'

      # checkout branch 3.0
      - name: Checkout branch 3.0
        if: ${{ startsWith(steps.branch-name.outputs.tag, '3.0') }} 
        uses: actions/checkout@v2
        with: 
          ref: '3.0'

      - name: Set Current Version
        run: |
          STEEDOS_VERSION=$(node -p 'require("./lerna.json").version')
          echo "STEEDOS_VERSION=${STEEDOS_VERSION}" >> $GITHUB_ENV
          echo "STEEDOS_VERSION=${STEEDOS_VERSION}"
        

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Aliyun Docker
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NINGXIA }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NINGXIA }}
      #     aws-region: cn-northwest-1

      # - name: Login to ECR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: 252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn

      - name: Pull and Push steedos-enterprise
        run: |
          SRC=steedos/steedos-enterprise:${{ env.STEEDOS_VERSION }}
          docker pull $SRC

          # docker tag $SRC 252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/steedos/steedos-enterprise:${{ env.STEEDOS_VERSION }}
          # docker push 252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/steedos/steedos-enterprise:${{ env.STEEDOS_VERSION }}

          docker tag $SRC registry.cn-shanghai.aliyuncs.com/steedos/steedos-community:${{ env.STEEDOS_VERSION }}
          docker tag $SRC registry.cn-shanghai.aliyuncs.com/steedos/steedos-enterprise:${{ env.STEEDOS_VERSION }}

          docker push registry.cn-shanghai.aliyuncs.com/steedos/steedos-community:${{ env.STEEDOS_VERSION }}
          docker push registry.cn-shanghai.aliyuncs.com/steedos/steedos-enterprise:${{ env.STEEDOS_VERSION }}

  npm-sync:
    runs-on: ubuntu-latest
    needs: npm-release 
    steps:
    
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.2
        with: 
          strip_tag_prefix: v

      # checkout branch 2.7
      - name: Checkout branch 2.7
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') }} 
        uses: actions/checkout@v2
        with: 
          ref: '2.7'

      # checkout branch 3.0
      - name: Checkout branch 3.0
        if: ${{ startsWith(steps.branch-name.outputs.tag, '3.0') }} 
        uses: actions/checkout@v2
        with: 
          ref: '3.0'
          
      - name: 3.0 Use Node.js 22
        uses: actions/setup-node@v4
        if: ${{ startsWith(steps.branch-name.outputs.tag, '3.0') }} 
        with:
          node-version: 22
          cache: "yarn"

      - name: 2.7 Use Node.js 14
        uses: actions/setup-node@v4
        if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') }} 
        with:
          node-version: 14
          cache: "yarn"

      - name: Sync cnpm
        env:
          CI: true
        run: |
          yarn
          yarn sync

