name: Release Please

on:
  push:
    branches:
      - '3.0'
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: steedos-platform
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          
      # Publish to NPM when release is created
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --immutable
        
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: yarn build
        
      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          yarn lerna publish from-package --yes --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
